const prefix = 'leagues';

export default {
  FETCH_LEAGUES: `${prefix}/FETCH_LEAGUES`,
  FETCH_LEAGUES_SUCCEEDED: `${prefix}/FETCH_LEAGUES_SUCCEEDED`,
  FETCH_LEAGUES_FAILED: `${prefix}/FETCH_LEAGUES_FAILED`,
  SEARCH: `${prefix}/SEARCH`,

  FETCH_LEAGUE: `${prefix}/FETCH_LEAGUE`,
  FETCH_LEAGUE_SUCCEEDED: `${prefix}/FETCH_LEAGUE_SUCCEEDED`,
  FETCH_LEAGUE_FAILED: `${prefix}/FETCH_LEAGUE_FAILED`,
};
